DEFAULTWORDLIST = 'wordlists/cain.txt'
DEFAULTOUTPUT = 'output/'
DEFAULTCRACKOUTPUT = 'crackoutput.txt'
DEFAULTFILELISTOUTPUT = 'fileoutput.txt'
DEFAULTENCODING = 'utf-8'
DEFAULTHYPERTEXTP = 'https://'
